articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:id>/delete/', views.delete, name='delete'),
    path('<int:id>/update/', views.update, name='update'),
]

modelForm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    # url에 들어가는것은 복수형으로 `-s` 를 붙인다.

]

articles/models.py
from django.db import models

# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

articles/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    # 기능 1 html 코드를 자동으로 만들어준다. 
    # 그래서 templates의 create.html의 7번째 {{form}}을 이용해서
    # articles의 views의 29번째줄에서 사용한다
    
    class Meta:
        model = Article
        fields = '__all__'

articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from .forms import ArticleForm

# Create your views here.

def index(request):
    articles = Article.objects.all()

    context = {
        'articles': articles,
    }

    return render(request, 'index.html', context)


def detail(request,id):
    article = Article.objects.get(id=id)

    context ={
        'article': article,
    }

    return render(request, 'detail.html', context)

def create(request):
    # 모든 경우의 수
    # 1. GET : From을 만들어서 html문서를 사용자에게 리턴
    # 2. POST invalid data : 데이터 검증에 실패한 경우
    #   => 검증에 성공한 데이터만 가지고 Form을 만드어 html 문서를 사용자에게 리턴
    # 3. POST ivalid data : 데이터 검증에 성공한 경우
    #   => DB에 데이터 저장 후 derail로 redirect

    # =============================================================================

    
    # 사용자가 입력한 데이터를 DB에 저장
    # 5. POST요청 (데이터가 잘못 들어온 경우)
    # 10. POST요청 (데이터가 옮바르게 들어온 경우)
    if request.method == 'POST':
        # 6. Form에 사용자가 입력한 정보(X)를 담아서 Form을 생성
        # 11. Form에 사용자가 입력한 정보(O)를 담아서 Form을 생선
        form = ArticleForm(request.POST)

        # request.POST를 통해 form에 들어온 데이터가
        # 형식에 맞게 들어왔는지 확인하는 과정
        # 7. Form을 검증 (검증에 실패)
        # 12. Form을 검증 (검증에 성공)
        if form.is_valid():
            # 13. Form을 저장하고 그 결과를 article 변수에 저장
            article = form.save()
            # 14. detail 페이지로 redirect
            return redirect('articles:detail', id=article.id)
        # else:
        #     pass
        #     form = ArticleForm()

        #     context = {
        #         'form' : form,
        #     }
        #     return render(request, 'create.html', context)

    # new에 해당하는 기능
    # 사용자가 데이터를 입력 할 수 있도록 빈 종이를 리턴


    # 1. GET 요청
    else:   
        # 2. 비어있는 From을 만들어서
        form = ArticleForm()

        # 3. context dict에 담고
        # 8. 검증에 실패한 Form을 context dict에 담고
        context = {
            'form': form,
        }
        # 4. create.html을 랜더링
        # 9. create.html을 랜더링
        return render(request, 'create.html', context)
    

def delete(request, id):
    article = Article.objects.get(id=id)

    article.delete()

    return redirect('articles:index')

def update(request, id):
    article = Article.objects.get(id=id)

    if request.method == 'POST':
        form = ArticleForm(request.POST, instance=article)
        #request.POST 새로운 데이터 /  instance=article 기존 데이터

        if form.is_valid():
            form.save()
            return redirect('articles:detail', id=id)

            #위와 같이 작동한다.
            # article = form.save()
            # return redirect('articles:detail', id=article.id)
            
    else:
        form = ArticleForm(instance=article)
        #기존 정보를 instance에 넣는다.

    context = {
        'form': form,
    }

    return render(request, 'update.html', context)

articles/templates/detail.html
{% extends 'base.html'%}

{% block body %}

<h1>{{article.title}}</h1>
<p>{{article.content}}</p>
<p>{{article.created_at}}</p>
<p>{{article.updated_at}}</p>

<a href="{% url 'articles:update' id=article.id %}">update</a>
<a href="{% url 'articles:delete' id=article.id %}">delete</a>

{% endblock %}

articles/templates/index.html
{% extends 'base.html'%}

{% block body %}
<h1>index</h1>

    {% for article in articles %}
        <p>{{article.title}}</p>
        <a href="{% url 'articles:detail' id=article.id%}">detail</a>
        <!-- detail에 url을 설정해 준다 위치는 article의 urls.py와 연결 -->
        <!-- 이 detail 버튼을 누르면 아티클 url의 8번째 중로 간다 -->
         

        <hr>
    {% endfor %}

{% endblock %}

articles/templates/update.html
{% extends 'base.html'%}

{% block body %}

<form action="" method="POST">
    {% csrf_token %}
    {{form}}
    <input type="submit">
</form>


{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <a href="{% url 'articles:index' %}">Home</a>
    <a href="{% url 'articles:create' %}">Create</a>
    
    {% block body %}

    {% endblock %}
</body>
</html>

templates/create.html
{% extends 'base.html'%}

{% block body %}

    <form action="" method="POST">
        {% csrf_token %}
        {{form}}
        <!-- 안에 여러가지 있는 데이터(이름, 주소, 번호 등등)을 form으로 묶어줌 -->
        <input type="submit">
        <!-- submit 버튼을 누를떄 가는 위치는 위에 action에 넣어준다. -->

    </form>

{% endblock %}